import { tokens } from "./tokens";

const b = tokens.brand;
const a = tokens.alias;

export const colorSchemes = {
  light: {
    palette: {
      primary: {
        50: b["blue-50"],
        100: b["blue-100"],
        200: b["blue-200"],
        300: b["blue-300"],
        400: b["blue-400"],
        500: b["blue-500"],
        600: b["blue-600"],
        700: b["blue-700"],
        800: b["blue-800"],
        900: b["blue-900"],
        solidBg: a["interactive-brand-default"],
        solidHoverBg: a["interactive-brand-hover"],
        solidActiveBg: a["interactive-brand-pressed"],
        solidColor: a["content-on-color"],
        softBg: a["interactive-soft-default"],
        softHoverBg: a["interactive-soft-hover"],
        softActiveBg: a["interactive-soft-pressed"],
        softColor: a["content-brand-default"],
        outlinedBorder: a["border-brand-subtle"],
        outlinedColor: a["content-brand-default"],
        outlinedHoverBg: a["interactive-outlined-hover"],
        outlinedActiveBg: a["interactive-outlined-pressed"],
        plainColor: a["content-brand-default"],
        plainHoverBg: a["interactive-ghost-hover"],
        plainActiveBg: a["interactive-ghost-pressed"],
      },
      neutral: {
        50: b["slate-50"],
        100: b["slate-100"],
        200: b["slate-200"],
        300: b["slate-300"],
        400: b["slate-400"],
        500: b["slate-500"],
        600: b["slate-600"],
        700: b["slate-700"],
        800: b["slate-800"],
        900: b["slate-900"],
        solidBg: a["bg-neutral-bold"],
        solidHoverBg: b["slate-900"],
        solidActiveBg: b["slate-950"],
        solidColor: a["content-inverse"],
        softBg: a["interactive-secondary-default"],
        softHoverBg: a["interactive-secondary-hover"],
        softActiveBg: a["interactive-secondary-pressed"],
        softColor: a["content-default"],
        outlinedBorder: a["border-default"],
        outlinedColor: a["content-default"],
        outlinedHoverBg: a["interactive-outlined-hover"],
        outlinedActiveBg: a["interactive-outlined-pressed"],
        plainColor: a["content-default"],
        plainHoverBg: a["interactive-ghost-hover"],
        plainActiveBg: a["interactive-ghost-pressed"],
      },
      danger: {
        50: b["red-50"],
        100: b["red-100"],
        200: b["red-200"],
        300: b["red-300"],
        400: b["red-400"],
        500: b["red-500"],
        600: b["red-600"],
        700: b["red-700"],
        800: b["red-800"],
        900: b["red-900"],
        solidBg: a["interactive-danger-default"],
        solidHoverBg: a["interactive-danger-hover"],
        solidActiveBg: a["interactive-danger-pressed"],
        solidColor: a["content-on-color"],
        softBg: a["interactive-danger-soft-default"],
        softHoverBg: a["interactive-danger-soft-hover"],
        softActiveBg: a["interactive-danger-soft-pressed"],
        softColor: a["content-danger-default"],
        outlinedBorder: a["border-danger-suble"],
        outlinedColor: a["content-danger-default"],
        outlinedHoverBg: b["red-50"],
        outlinedActiveBg: b["red-100"],
        plainColor: a["content-danger-default"],
        plainHoverBg: b["red-50"],
        plainActiveBg: b["red-100"],
      },
      success: {
        50: b["green-50"],
        100: b["green-100"],
        200: b["green-200"],
        300: b["green-300"],
        400: b["green-400"],
        500: b["green-500"],
        600: b["green-600"],
        700: b["green-700"],
        800: b["green-800"],
        900: b["green-900"],
        solidBg: a["bg-success-default"],
        solidHoverBg: a["bg-success-bold"],
        solidActiveBg: a["bg-success-strong"],
        solidColor: a["content-on-color"],
        softBg: a["bg-success-subtle"],
        softHoverBg: a["bg-success-soft"],
        softActiveBg: b["green-200"],
        softColor: a["content-success-default"],
        outlinedBorder: a["border-success-subtle"],
        outlinedColor: a["content-success-default"],
        outlinedHoverBg: b["green-50"],
        outlinedActiveBg: b["green-100"],
        plainColor: a["content-success-default"],
        plainHoverBg: b["green-50"],
        plainActiveBg: b["green-100"],
      },
      warning: {
        50: b["amber-50"],
        100: b["amber-100"],
        200: b["amber-200"],
        300: b["amber-300"],
        400: b["amber-400"],
        500: b["amber-500"],
        600: b["amber-600"],
        700: b["amber-700"],
        800: b["amber-800"],
        900: b["amber-900"],
        solidBg: a["bg-warning-default"],
        solidHoverBg: a["bg-warning-bold"],
        solidActiveBg: a["bg-warning-strong"],
        solidColor: a["content-on-color"],
        softBg: a["bg-warning-subtle"],
        softHoverBg: a["bg-warning-soft"],
        softActiveBg: b["amber-200"],
        softColor: a["content-warning-default"],
        outlinedBorder: a["border-warning-subtle"],
        outlinedColor: a["content-warning-default"],
        outlinedHoverBg: b["amber-50"],
        outlinedActiveBg: b["amber-100"],
        plainColor: a["content-warning-default"],
        plainHoverBg: b["amber-50"],
        plainActiveBg: b["amber-100"],
      },
      background: {
        body: a["bg-default"],
        surface: a["bg-raised"],
        level1: a["bg-subtle"],
        level2: a["bg-muted"],
        level3: a["bg-dim"],
      },
      text: {
        primary: a["content-default"],
        secondary: a["content-subtle"],
        tertiary: a["content-muted"],
      },
      divider: a["border-default"],
      focusVisible: a["border-focus"],
    },
  },
};
